Update .gitlab-ci.yml file

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -1,13 +1,70 @@
-# You can override the included template(s) by including variable overrides
-# SAST customization: https://docs.gitlab.com/ee/user/application_security/sast/#customizing-the-sast-settings
-# Secret Detection customization: https://docs.gitlab.com/ee/user/application_security/secret_detection/#customizing-settings
-# Dependency Scanning customization: https://docs.gitlab.com/ee/user/application_security/dependency_scanning/#customizing-the-dependency-scanning-settings
-# Container Scanning customization: https://docs.gitlab.com/ee/user/application_security/container_scanning/#customizing-the-container-scanning-settings
-# Note that environment variables can be set in several places
-# See https://docs.gitlab.com/ee/ci/variables/#cicd-variable-precedence
+image: registry.gitlab.nxs360.com/docker/php:7.4-cli
+
 stages:
-- test
-sast:
-  stage: test
-include:
-- template: Security/SAST.gitlab-ci.yml
+    - validation
+    - deploy
+    - release
+
+tests:coverage:
+    stage: validation
+    script:
+        - composer validate
+        - composer install
+        - composer cs-check
+        - composer md-check
+    coverage: '/^\s*Lines:\s*\d+.\d+\%/'
+    artifacts:
+        expire_in: 30 days
+        paths:
+            - tests/_output/
+
+pages:
+    image: ruby:2.7
+    stage: deploy
+    script:
+        - "mv tests/_output/coverage/ public/"
+    artifacts:
+        expire_in: 30 days
+        paths:
+            - public
+    only:
+        - master
+
+# https://gitlab.nxs360.com/help/user/packages/composer_repository/index#publish-a-composer-package-by-using-cicd
+deploy:composer:
+    stage: deploy
+    script:
+        - version=$([[ -z "$CI_COMMIT_TAG" ]] && echo "branch=$CI_COMMIT_REF_NAME" || echo "tag=$CI_COMMIT_TAG")
+        - response=$(curl -s -w "\n%{http_code}" $insecure --data $version $URL)
+        - code=$(echo "$response" | tail -n 1)
+        - body=$(echo "$response" | head -n 1)
+        # Output state information
+        - |
+            if [ $code -eq 201 ]; then
+              echo "Package created - Code $code - $body";
+            else
+              echo "Could not create package - Code $code - $body";
+              exit 1
+            fi
+    variables:
+        URL: "${CI_API_V4_URL}/projects/$CI_PROJECT_ID/packages/composer?job_token=$CI_JOB_TOKEN"
+    rules:
+        - if: $CI_MERGE_REQUEST_ID
+          when: never
+        - if: $CI_COMMIT_TAG =~ /^?[0-9]+[.][0-9]+([.][0-9]+)?$/
+
+
+# https://docs.gitlab.com/ee/user/project/releases/release_cicd_examples.html#create-a-release-when-a-git-tag-is-created
+release_job:
+    stage: release
+    image: registry.gitlab.com/gitlab-org/release-cli:latest
+    rules:
+        - if: $CI_COMMIT_TAG                 # Run this job when a tag is created
+    script:
+        - echo "running release_job"
+    release:                               # See https://docs.gitlab.com/ee/ci/yaml/#release for available properties
+        tag_name: '$CI_COMMIT_TAG'
+        description: '$CI_COMMIT_TAG'
+
+variables:
+    COMPOSER_AUTH: '{"gitlab-oauth":{"gitlab.nxs360.com":"vnzsASLw7YzcAzPYN6_v"}}'
